events {}
http {
  upstream api_upstream { server api:3000; }
  upstream dashboard_upstream { server dashboard:3001; }

  server {
    listen 80;

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://api_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
      proxy_pass http://dashboard_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
